const UNIT_LIMIT = 10000000000
const QUANTITY_TIMIT = 1000

const DATETIME_FORMAT = 'DD-MM-YYYY HH:mm:ss'
const DATE_FORMAT = 'DD-MM-YYYY'
const DATE_TEXT_FORMAT = 'LL'

const PRODUCTS_LIST_KEY = 'productsList'

export {
  UNIT_LIMIT,
  QUANTITY_TIMIT,
  DATETIME_FORMAT,
  DATE_FORMAT,
  DATE_TEXT_FORMAT,
  PRODUCTS_LIST_KEY
}
