const UNIT_LIMIT = 10000000000
const QUANTITY_TIMIT = 1000

const DATETIME_FORMAT = 'DD-MM-YYYY HH:mm:ss'
const DATE_FORMAT = 'DD-MM-YYYY'
const DATE_TEXT_FORMAT = 'LL'
const MONTH_NAME_FORMAT = 'MMMM'
const MONTH_NUMBER_FORMAT = 'MM'

export {
  UNIT_LIMIT,
  QUANTITY_TIMIT,
  DATETIME_FORMAT,
  DATE_FORMAT,
  DATE_TEXT_FORMAT,
  MONTH_NAME_FORMAT,
  MONTH_NUMBER_FORMAT
}
