const PRINCIPAL_SCREEN_KEY = 'principalScreen'
const NEW_PURCHASE_SCREEN_KEY = 'newPurchaseScreen'
const VIEW_PURCHASES_SCREEN_KEY = 'viewPurchasesScreen'
const APP_SETTINGS_SCREEN_KEY = 'appSettingsScreen'
const STATISTICS_SCREEN_KEY = 'statisticsScreen'

const SCREEN_KEYS = [
  PRINCIPAL_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY,
  APP_SETTINGS_SCREEN_KEY,
  STATISTICS_SCREEN_KEY
]

export {
  PRINCIPAL_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY,
  APP_SETTINGS_SCREEN_KEY,
  STATISTICS_SCREEN_KEY,
  SCREEN_KEYS
}
