const PRINCIPAL_SCREEN_KEY: string = 'principalScreen'
const NEW_REGISTER_SCREEN_KEY: string = 'newRegisterScreen'
const NEW_PURCHASE_SCREEN_KEY: string = 'newPurchaseScreen'
const VIEW_PURCHASES_SCREEN_KEY: string = 'viewPurchasesScreen'
const NEW_BILL_SCREEN_KEY: string = 'newBillScreen'
const APP_SETTINGS_SCREEN_KEY: string = 'appSettingsScreen'
const STATISTICS_SCREEN_KEY: string = 'statisticsScreen'

const SCREEN_KEYS = [
  PRINCIPAL_SCREEN_KEY,
  NEW_REGISTER_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY,
  NEW_BILL_SCREEN_KEY,
  APP_SETTINGS_SCREEN_KEY,
  STATISTICS_SCREEN_KEY
] as const

export {
  PRINCIPAL_SCREEN_KEY,
  NEW_REGISTER_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY,
  NEW_BILL_SCREEN_KEY,
  APP_SETTINGS_SCREEN_KEY,
  STATISTICS_SCREEN_KEY,
  SCREEN_KEYS
}
