const PRINCIPAL_SCREEN_KEY = 'PrincipalScreen'
const NEW_PURCHASE_SCREEN_KEY = 'NewPurchaseScreen'
const VIEW_PURCHASES_SCREEN_KEY = 'ViewPurchasesScreen'

const SCREEN_KEYS = [
  PRINCIPAL_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY
]

export {
  PRINCIPAL_SCREEN_KEY,
  NEW_PURCHASE_SCREEN_KEY,
  VIEW_PURCHASES_SCREEN_KEY,
  SCREEN_KEYS
}